// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// winflashr
void winflashr(int count);
RcppExport SEXP winflashr_winflashr(SEXP countSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type count(countSEXP);
    winflashr(count);
    return R_NilValue;
END_RCPP
}
