# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Make Rstudio window blink
#' @param count number of times to blink
#' @examples
#' winflash(10)
winflash <- function(count = 1L) {
    invisible(.Call('winflashr_winflash', PACKAGE = 'winflashr', count))
}

